### ISSUE TITLE
Error generating resources

### ISSUE THREAD

**Issue by giles247** [ruudy-es/Metronic-Crud-Generator-Bundle#1]
When doing:
php app/console ruudy:metronic-crud-generator:generate

while generating ApplicationMetronicBackEndBundle.php I get error:

Warning: file_get_contents(../Resources/skeleton/bundle/bundle.mustache): failed to open stream: no such file or directory

Running the same for the MetronicBundle worked ok. I'm running on a wamp setup, and only reference I could find to similar error was something to do with path being too long?

Anyway, result is I cannot generate resources.

**Comment by ruudy-es** [comment]
Solved on https://github.com/ruudy-es/Metronic-Crud-Generator-Bundle/commit/c69660c4267198f0dcaad59d97a4d5cba5b2450d
